pipeline:
  install:
    image: fpfis/php71-dev
    commands:
      - composer self-update
      - composer install
  test:
    image: fpfis/php71-dev
    commands:
      - robo project:install
      - ./vendor/bin/drush --root=$PWD/build --debug runserver :8888 > ~/debug.txt 2>&1 &
      - sleep 4s
      - ./vendor/bin/grumphp run
      - ./vendor/bin/behat
