language: php
php:
  - 5.6
  - 7.0

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin

install:
  - composer self-update
  - composer install
  - phantomjs --webdriver=4444 > /dev/null &

before_script:
  - robo project:setup
  - robo project:install
  - drush --root=$PWD/build --debug runserver :80 > ~/debug.txt 2>&1 &
  - sleep 4s

script:
  - grumphp run
  - behat

notifications:
  email: false
