language: php
php:
  - 5.6
  - 7.0

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin

install:
  - composer self-update
  - composer install
  - robo project:setup
  - robo project:install

script:
  - grumphp run

notifications:
  email: false
